sudo: false
language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"

before_script:
  - git submodule update --init --recursive
  - cd node_modules/remotestorage-oauth && npm install
  - cd node_modules/vault-cipher && npm install
